apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::754074880371:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::754074880371:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EJ3JBU9JV1CW
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-20T16:28:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-20T16:28:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1461"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ba3277ce-1690-4077-803f-83a4b3cfe758
